version: '3.8'

services:
  digi-port:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digi-port-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - PORT=3000
